[package]
name = "community-factory"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
community-nft = { path = "../community-nft" }
community-governor = { path = "../community-governor" }
stellar-governance = { workspace = true }
